### ISSUE TITLE
Data_Processing/Export/Image_exported_count

### ISSUE THREAD

**Issue by JoleenBroadfield** [pantheracorp/PantheraIDS_Features#21] opened 2019-01-21 07:53 UTC
Discrepancy between the amount of images "successfully exported" and amount of images actually exported.
Amount of images "successfully exported" take in account duplicate images -> to amend in code.

**Comment by Shannon-Dubay** [comment] 2020-06-24 15:22
I am not sure what "duplicate images" refers to- does this mean images that have the same image name (how is this possible?) or does this mean images that have different image names but contain the same visual (appears as though the image was duplicated and given 2 different names?)

**Comment by Shannon-Dubay** [comment] 2020-07-23 17:13
can't recreate this @RossPitman do you know of any datasets that have duplicate images for me to test with?

**Comment by RossPitman** [comment] 2020-09-14 19:57
Duplicate of another issue.

**Closed by RossPitman** 2020-09-14 19:57 UTC
